
package pepmhc.neo;

import java.util.Collection;

import jam.lang.JamException;

import jean.hla.PeptideSource;
import jean.hugo.HugoPeptideTable;
import jean.hugo.HugoSymbol;
import jean.peptide.Peptide;

/**
 * Stores neo-peptides generated by antigen processing of mutated
 * genes along with self-peptides generated from the same genes.
 */
public final class PeptideSourceView {
    private final HugoPeptideTable neoPeptideTable;
    private final HugoPeptideTable selfPeptideTable;
    private final HugoPeptideTable selfReferenceTable;

    private PeptideSourceView(HugoPeptideTable neoPeptideTable,
                              HugoPeptideTable selfPeptideTable,
                              HugoPeptideTable selfReferenceTable) {
        this.neoPeptideTable = neoPeptideTable;
        this.selfPeptideTable = selfPeptideTable;
        this.selfReferenceTable = selfReferenceTable;
    }

    /**
     * Creates a new peptide-source table from its constituent data
     * tables.
     *
     * @param neoPeptideTable the neo-peptides generated by antigen
     * processing of mutated genes.
     *
     * @param selfPeptideTable the self-peptides generated by antigen
     * processing of mutated genes.
     *
     * @param selfReferenceTable the reference self-peptidome to be
     * used for unmutated genes.
     *
     * @return the new peptide source table.
     */
    public static PeptideSourceView create(HugoPeptideTable neoPeptideTable,
                                           HugoPeptideTable selfPeptideTable,
                                           HugoPeptideTable selfReferenceTable) {
        return new PeptideSourceView(neoPeptideTable, selfPeptideTable, selfReferenceTable);
    }

    /**
     * Returns the peptides of a given type generated by antigen
     * processing of mutated genes.
     *
     * @param source the peptide type: "neo" or "self".
     *
     * @return the peptides of the specified type.
     */
    public HugoPeptideTable getPeptideTable(PeptideSource source) {
        switch (source) {
        case NEO:
            return neoPeptideTable;

        case SELF:
            return selfPeptideTable;

        default:
            throw JamException.runtime("Unknown peptide source: [%s].", source);
        }
    }

    /**
     * Returns the neo-peptides generated by antigen processing of
     * mutated genes.
     *
     * @return the neo-peptides generated by antigen processing of
     * mutated genes.
     */
    public HugoPeptideTable getNeoPeptideTable() {
        return neoPeptideTable;
    }

    /**
     * Returns the neo-peptides generated by antigen processing for
     * a given gene.
     *
     * @param hugoSymbol the HUGO symbol for the gene of interest.
     *
     * @return all neo-peptides generated from antigen processing of
     * the specified gene (will be empty for unmutated genes).
     */
    public Collection<Peptide> getNeoPeptides(HugoSymbol hugoSymbol) {
        return neoPeptideTable.get(hugoSymbol);
    }

    /**
     * Returns the self-peptides generated by antigen processing of
     * mutated genes.
     *
     * @return the self-peptides generated by antigen processing of
     * mutated genes.
     */
    public HugoPeptideTable getSelfPeptideTable() {
        return selfPeptideTable;
    }

    /**
     * Returns the self-peptides generated by antigen processing for
     * a given gene.
     *
     * @param hugoSymbol the HUGO symbol for the gene of interest.
     *
     * @return all self-peptides generated from antigen processing of
     * the specified gene (the reference self-peptidome for unmutated
     * genes).
     */
    public Collection<Peptide> getSelfPeptides(HugoSymbol hugoSymbol) {
        if (selfPeptideTable.contains(hugoSymbol))
            return selfPeptideTable.get(hugoSymbol);
        else
            return selfReferenceTable.get(hugoSymbol);
    }

    /**
     * Returns the table containing the reference self-peptidome (for
     * genes that are not mutated).
     *
     * @return the table containing the reference self-peptidome (for
     * genes that are not mutated).
     */
    public HugoPeptideTable getSelfReferenceTable() {
        return selfReferenceTable;
    }
}
